import re
raw=open('public/index.html',encoding='utf-8').read()
print('--- header close + backdrop ---')
i=raw.find('nav-backdrop')
print(raw[i-140:i+120])
print()
print('--- before body close ---')
j=raw.find('mobile-cta')
print(raw[j-180:j+340])
print()
t=open('public/best-payment-methods-pokies-australia-2026.html',encoding='utf-8').read()
k=t.find('table-wrap')
print('--- table wrap ---')
print(t[k-40:k+140])
print()
print('viewport meta:', re.search(r'name="viewport" content="[^"]*"', t).group(0))
print('body tag:', re.search(r'<body[^>]*>', t).group(0))
